// Code generated by go-swagger; DO NOT EDIT.

package client

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"
	httptransport "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/cicdteam/go-deribit/client/account_management"
	"github.com/cicdteam/go-deribit/client/internal_swagger"
	"github.com/cicdteam/go-deribit/client/market_data"
	"github.com/cicdteam/go-deribit/client/private"
	"github.com/cicdteam/go-deribit/client/public"
	"github.com/cicdteam/go-deribit/client/supporting"
	"github.com/cicdteam/go-deribit/client/trading"
	"github.com/cicdteam/go-deribit/client/wallet"
	"github.com/cicdteam/go-deribit/client/websocket_only"
)

// Default deribit API HTTP client.
var Default = NewHTTPClient(nil)

const (
	// DefaultHost is the default Host
	// found in Meta (info) section of spec file
	DefaultHost string = "localhost:8082"
	// DefaultBasePath is the default BasePath
	// found in Meta (info) section of spec file
	DefaultBasePath string = "/api/v2"
)

// DefaultSchemes are the default schemes found in Meta (info) section of spec file
var DefaultSchemes = []string{"http"}

// NewHTTPClient creates a new deribit API HTTP client.
func NewHTTPClient(formats strfmt.Registry) *DeribitAPI {
	return NewHTTPClientWithConfig(formats, nil)
}

// NewHTTPClientWithConfig creates a new deribit API HTTP client,
// using a customizable transport config.
func NewHTTPClientWithConfig(formats strfmt.Registry, cfg *TransportConfig) *DeribitAPI {
	// ensure nullable parameters have default
	if cfg == nil {
		cfg = DefaultTransportConfig()
	}

	// create transport and client
	transport := httptransport.New(cfg.Host, cfg.BasePath, cfg.Schemes)
	return New(transport, formats)
}

// New creates a new deribit API client
func New(transport runtime.ClientTransport, formats strfmt.Registry) *DeribitAPI {
	// ensure nullable parameters have default
	if formats == nil {
		formats = strfmt.Default
	}

	cli := new(DeribitAPI)
	cli.Transport = transport
	cli.AccountManagement = account_management.New(transport, formats)
	cli.InternalSwagger = internal_swagger.New(transport, formats)
	cli.MarketData = market_data.New(transport, formats)
	cli.Private = private.New(transport, formats)
	cli.Public = public.New(transport, formats)
	cli.Supporting = supporting.New(transport, formats)
	cli.Trading = trading.New(transport, formats)
	cli.Wallet = wallet.New(transport, formats)
	cli.WebsocketOnly = websocket_only.New(transport, formats)
	return cli
}

// DefaultTransportConfig creates a TransportConfig with the
// default settings taken from the meta section of the spec file.
func DefaultTransportConfig() *TransportConfig {
	return &TransportConfig{
		Host:     DefaultHost,
		BasePath: DefaultBasePath,
		Schemes:  DefaultSchemes,
	}
}

// TransportConfig contains the transport related info,
// found in the meta section of the spec file.
type TransportConfig struct {
	Host     string
	BasePath string
	Schemes  []string
}

// WithHost overrides the default host,
// provided by the meta section of the spec file.
func (cfg *TransportConfig) WithHost(host string) *TransportConfig {
	cfg.Host = host
	return cfg
}

// WithBasePath overrides the default basePath,
// provided by the meta section of the spec file.
func (cfg *TransportConfig) WithBasePath(basePath string) *TransportConfig {
	cfg.BasePath = basePath
	return cfg
}

// WithSchemes overrides the default schemes,
// provided by the meta section of the spec file.
func (cfg *TransportConfig) WithSchemes(schemes []string) *TransportConfig {
	cfg.Schemes = schemes
	return cfg
}

// DeribitAPI is a client for deribit API
type DeribitAPI struct {
	AccountManagement account_management.ClientService

	InternalSwagger internal_swagger.ClientService

	MarketData market_data.ClientService

	Private private.ClientService

	Public public.ClientService

	Supporting supporting.ClientService

	Trading trading.ClientService

	Wallet wallet.ClientService

	WebsocketOnly websocket_only.ClientService

	Transport runtime.ClientTransport
}

// SetTransport changes the transport on the client and all its subresources
func (c *DeribitAPI) SetTransport(transport runtime.ClientTransport) {
	c.Transport = transport
	c.AccountManagement.SetTransport(transport)
	c.InternalSwagger.SetTransport(transport)
	c.MarketData.SetTransport(transport)
	c.Private.SetTransport(transport)
	c.Public.SetTransport(transport)
	c.Supporting.SetTransport(transport)
	c.Trading.SetTransport(transport)
	c.Wallet.SetTransport(transport)
	c.WebsocketOnly.SetTransport(transport)
}
