// Code generated by go-swagger; DO NOT EDIT.

package trading

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/cicdteam/go-deribit/models"
)

// GetPrivateTradehistoryReader is a Reader for the GetPrivateTradehistory structure.
type GetPrivateTradehistoryReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetPrivateTradehistoryReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetPrivateTradehistoryOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetPrivateTradehistoryOK creates a GetPrivateTradehistoryOK with default headers values
func NewGetPrivateTradehistoryOK() *GetPrivateTradehistoryOK {
	return &GetPrivateTradehistoryOK{}
}

/*GetPrivateTradehistoryOK handles this case with default header values.

foo
*/
type GetPrivateTradehistoryOK struct {
	Payload *models.PrivateTradehistoryResponse
}

func (o *GetPrivateTradehistoryOK) Error() string {
	return fmt.Sprintf("[GET /private/tradehistory][%d] getPrivateTradehistoryOK  %+v", 200, o.Payload)
}

func (o *GetPrivateTradehistoryOK) GetPayload() *models.PrivateTradehistoryResponse {
	return o.Payload
}

func (o *GetPrivateTradehistoryOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.PrivateTradehistoryResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
