// Code generated by go-swagger; DO NOT EDIT.

package trading

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/cicdteam/go-deribit/models"
)

// GetPrivateOrderhistoryReader is a Reader for the GetPrivateOrderhistory structure.
type GetPrivateOrderhistoryReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetPrivateOrderhistoryReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetPrivateOrderhistoryOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetPrivateOrderhistoryOK creates a GetPrivateOrderhistoryOK with default headers values
func NewGetPrivateOrderhistoryOK() *GetPrivateOrderhistoryOK {
	return &GetPrivateOrderhistoryOK{}
}

/*GetPrivateOrderhistoryOK handles this case with default header values.

foo
*/
type GetPrivateOrderhistoryOK struct {
	Payload *models.PrivateOrderhistoryResponse
}

func (o *GetPrivateOrderhistoryOK) Error() string {
	return fmt.Sprintf("[GET /private/orderhistory][%d] getPrivateOrderhistoryOK  %+v", 200, o.Payload)
}

func (o *GetPrivateOrderhistoryOK) GetPayload() *models.PrivateOrderhistoryResponse {
	return o.Payload
}

func (o *GetPrivateOrderhistoryOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.PrivateOrderhistoryResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
