// Code generated by go-swagger; DO NOT EDIT.

package internal_swagger

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// New creates a new internal swagger API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

/*
Client for internal swagger API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientService is the interface for Client methods
type ClientService interface {
	GetPrivateDatatable(params *GetPrivateDatatableParams) (*GetPrivateDatatableOK, error)

	GetPublicGetFooter(params *GetPublicGetFooterParams) (*GetPublicGetFooterOK, error)

	GetPublicGetOptionMarkPrices(params *GetPublicGetOptionMarkPricesParams) (*GetPublicGetOptionMarkPricesOK, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
  GetPrivateDatatable this is a private API endpoint intended for the user interface this API is subject to change and should not be used outside the deribit interface
*/
func (a *Client) GetPrivateDatatable(params *GetPrivateDatatableParams) (*GetPrivateDatatableOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetPrivateDatatableParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "GetPrivateDatatable",
		Method:             "GET",
		PathPattern:        "/private/datatable",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &GetPrivateDatatableReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*GetPrivateDatatableOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for GetPrivateDatatable: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
  GetPublicGetFooter gets information to be displayed in the footer of the website
*/
func (a *Client) GetPublicGetFooter(params *GetPublicGetFooterParams) (*GetPublicGetFooterOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetPublicGetFooterParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "GetPublicGetFooter",
		Method:             "GET",
		PathPattern:        "/public/get_footer",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &GetPublicGetFooterReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*GetPublicGetFooterOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for GetPublicGetFooter: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
  GetPublicGetOptionMarkPrices retrives market prices and its implied volatility of options instruments
*/
func (a *Client) GetPublicGetOptionMarkPrices(params *GetPublicGetOptionMarkPricesParams) (*GetPublicGetOptionMarkPricesOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetPublicGetOptionMarkPricesParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "GetPublicGetOptionMarkPrices",
		Method:             "GET",
		PathPattern:        "/public/get_option_mark_prices",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http"},
		Params:             params,
		Reader:             &GetPublicGetOptionMarkPricesReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*GetPublicGetOptionMarkPricesOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for GetPublicGetOptionMarkPrices: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
